spring:
  application:
    name: '@project.artifactId@'
  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: false


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_versioned_data: true

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_db_multi_file?rewriteBatchedInserts=true
    username: root
    password: root123



#batch:
#  imports:
#    - name: customer
#      file: src/main/resources/customers.csv
#      table: stg_customer
#      columns: id,first_name,last_name,email,gender,contact,country,dob
#    - name: order
#      file: src/main/resources/orders.csv
#      table: stg_order
#      columns: id,customer_id,order_date,amount,status
#    - name: invoice
#      file: src/main/resources/invoices.csv
#      table: stg_invoice
#      columns: id,order_id,invoice_date,total
