
spring:
  application:
    name: '@project.artifactId@'
  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: false


  jpa:
    #hibernate:
    #  ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.jdbc.batch_versioned_data: true

  datasource:
    url: jdbc:postgresql://localhost:5432/batch_db_multi_file?rewriteBatchedInserts=true
    username: root
    password: root123


batch:
  import:
    #customersFile: "src/main/resources/customers.csv"
    #ordersFile: "src/main/resources/orders.csv"
    customersFile: "./data/customers.csv"
    ordersFile: "./data/orders.csv"
    allowedStatuses: [NEW, PAID, CANCELLED, SHIPPED, REFUNDED]
    allowedGenders: [Male, Female, Other, Unknown]
server:
  port: 8081



file:
  provider:
    base-url: http://localhost:8080

  download:
    directory: ./data